
SET search_path TO "payment";
begin;

create table if not exists payments (
    id integer not null  generated by default as identity,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    deleted_at timestamp default null,
    uuid uuid not null primary key,
    
    order_id uuid not null,
    shop_id uuid not null,
    customer_id uuid not null,
    amount float not null
);

create index if not exists idx_payment_list on payments (deleted_at, shop_id);

commit;